# arquivo de configuração centrao do PlatformIO para ESP32

[env:esp32dev]                      ; nome do "ambiente" (pode ter vários)
platform = espressif32              ; plataforma (família do chip)
board = esp32dev                    ; placa específica
framework = arduino                 ; framework de desenvolvimento
monitor_speed = 115200              ; baud rate do monitor serial
upload_speed = 921600               ; velocidade de gravação

lib_deps =                          ; lista de bibliotecas externas
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO